			if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6304bd93e5401',
	'title' => 'Description morphologique',
	'fields' => array(
		array(
			'key' => 'field_6304bda381ab9',
			'label' => 'Photo de la plante entière',
			'name' => 'photo_de_la_plante_entiere',
			'type' => 'image',
			'instructions' => 'Photo assez grande',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_6304bdd481aba',
			'label' => 'Le saviez-vous ?',
			'name' => 'le_saviez-vous_',
			'type' => 'text',
			'instructions' => 'Champs libre avec suggestions type : toxique, jeu, aspect historique, origine du nom...',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6304bdf681abb',
			'label' => 'Port de la plante',
			'name' => 'port_de_la_plante',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'herbacée' => 'herbacée',
				'arbrisseau' => 'arbrisseau',
				'arbre' => 'arbre',
				'liane' => 'liane',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6304be7c75bd9',
			'label' => 'Système sexuel',
			'name' => 'systeme_sexuel',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'hermaphrodite' => 'hermaphrodite',
				'monoïque (à préciser dans signes particulier)' => 'monoïque (à préciser dans signes particulier)',
				'dioïque (à préciser dans signes particulier)"' => 'dioïque (à préciser dans signes particulier)"',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6304c10075bda',
			'label' => 'Mode de vie',
			'name' => 'mode_de_vie',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6304bdf681abb',
						'operator' => '==',
						'value' => 'herbacée',
					),
				),
				array(
					array(
						'field' => 'field_6304bdf681abb',
						'operator' => '==',
						'value' => 'liane',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'terrestre' => 'terrestre',
				'aquatique' => 'aquatique',
				'épiphyte' => 'épiphyte',
				'parasite' => 'parasite',
				'hémiparasite' => 'hémiparasite',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_6304c15175bdc',
			'label' => 'Type de développement',
			'name' => 'type_de_developpement',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6304bdf681abb',
						'operator' => '==',
						'value' => 'herbacée',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'annuelle' => 'annuelle',
				'bisannuelle' => 'bisannuelle',
				'vivace' => 'vivace',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_6304c1bd75bdd',
			'label' => 'Forme biologique',
			'name' => 'forme_biologique',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6304bdf681abb',
						'operator' => '==',
						'value' => 'herbacée',
					),
				),
				array(
					array(
						'field' => 'field_6304bdf681abb',
						'operator' => '==',
						'value' => 'liane',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'géophyte à tubercule' => 'géophyte à tubercule',
				'géophyte à rhizome' => 'géophyte à rhizome',
				'géophyte à bulbe' => 'géophyte à bulbe',
				'hémicryptophyte' => 'hémicryptophyte',
				'hémicryptophyte à rosette' => 'hémicryptophyte à rosette',
				'hémicryptophyte cespiteux' => 'hémicryptophyte cespiteux',
				'chaméphyte' => 'chaméphyte',
				'hydrophyte' => 'hydrophyte',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
		array(
			'key' => 'field_6304c23d75be0',
			'label' => 'Hauteur maximale',
			'name' => 'hauteur_maximale',
			'type' => 'select',
			'instructions' => 'qui peut atteindre jusqu\'à .... de haut.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'10 cm' => '10 cm',
				'20 cm' => '20 cm',
				'40 cm' => '40 cm',
				'60 cm' => '60 cm',
				'80 cm' => '80 cm',
				'100 cm' => '100 cm',
				'120 cm' => '120 cm',
				'140 cm' => '140 cm',
				'160 cm' => '160 cm',
				'180 cm' => '180 cm',
				'2 m' => '2 m',
				'3 m' => '3 m',
				'4 m' => '4 m',
				'5 m' => '5 m',
				'10 m' => '10 m',
				'20 m' => '20 m',
				'30 m' => '30 m',
				'40 m' => '40 m',
				'50 m' => '50 m',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6304c46075be1',
			'label' => 'Pilosité de la plante entière',
			'name' => 'pilosite_de_la_plante_entiere',
			'type' => 'radio',
			'instructions' => 'Cette plante est...',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'entièrement glabre' => 'entièrement glabre',
				'entièrement recouverte de poils' => 'entièrement recouverte de poils',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6304c4aa75be2',
			'label' => 'Signe particulier',
			'name' => 'signe_particulier',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6304e1ece18b0',
			'label' => 'Tige',
			'name' => 'tige',
			'type' => 'group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6304c61a23918',
					'label' => 'Photo de tige',
					'name' => 'photo_tige',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_6304c66b23919',
					'label' => 'Tige aérienne',
					'name' => 'tige_aerienne',
					'type' => 'radio',
					'instructions' => 'La tige aérienne est ..., ..., ...,',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'visible' => 'visible',
						'visible une partie de l\'année' => 'visible une partie de l\'année',
						'non visible' => 'non visible',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304c6d52391a',
					'label' => 'Type de tige',
					'name' => 'type_de_tige',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304c66b23919',
								'operator' => '!=',
								'value' => 'non visible',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'dressée' => 'dressée',
						'rampante' => 'rampante',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304c8e02391b',
					'label' => 'Ramification',
					'name' => 'ramification',
					'type' => 'radio',
					'instructions' => 'ramifiée
non ramifiée',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304c66b23919',
								'operator' => '!=',
								'value' => 'non visible',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304c9402391c',
					'label' => 'Section de la tige',
					'name' => 'section_de_la_tige',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304c66b23919',
								'operator' => '!=',
								'value' => 'non visible',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'circulaire' => 'circulaire',
						'carrée' => 'carrée',
						'triangulaire' => 'triangulaire',
						'polygonale' => 'polygonale',
						'creuse' => 'creuse',
						'pleine' => 'pleine',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304c9762391d',
					'label' => 'Surface de la tige jeune',
					'name' => 'surface_de_la_tige_jeune',
					'type' => 'select',
					'instructions' => 'Sa surface est ... au moins quand elle est jeune.',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304c66b23919',
								'operator' => '!=',
								'value' => 'non visible',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'lisse' => 'lisse',
						'striée' => 'striée',
						'ailée' => 'ailée',
						'faiblement pubescente' => 'faiblement pubescente',
						'fortement pubsecente' => 'fortement pubsecente',
						'épineuse' => 'épineuse',
						'lenticellée' => 'lenticellée',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 1,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_6304ca5e58ca8',
					'label' => 'Surface de l\'écorce',
					'name' => 'surface_de_lecorce',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304c66b23919',
								'operator' => '!=',
								'value' => 'non visible',
							),
							array(
								'field' => 'field_6304bdf681abb',
								'operator' => '==',
								'value' => 'arbrisseau',
							),
						),
						array(
							array(
								'field' => 'field_6304bdf681abb',
								'operator' => '!=',
								'value' => 'arbre',
							),
							array(
								'field' => 'field_6304c66b23919',
								'operator' => '!=',
								'value' => 'non visible',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'lisse' => 'lisse',
						'cannelée' => 'cannelée',
						'crevassée' => 'crevassée',
						'striée verticalement' => 'striée verticalement',
						'striée horizontalement' => 'striée horizontalement',
						'plissée' => 'plissée',
						'formant des plaques' => 'formant des plaques',
						'liégeuse formant des écailles' => 'liégeuse formant des écailles',
						'liégeuse' => 'liégeuse',
						'formant des lanières' => 'formant des lanières',
						'formant des lenticelle' => 'formant des lenticelle',
					),
					'default_value' => array(
					),
					'allow_null' => 0,
					'multiple' => 1,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_6304cd8ee66c2',
					'label' => 'Couleur du tronc',
					'name' => 'couleur_du_tronc',
					'type' => 'select',
					'instructions' => 'et de couleur ... .',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304c66b23919',
								'operator' => '!=',
								'value' => 'non visible',
							),
							array(
								'field' => 'field_6304bdf681abb',
								'operator' => '!=',
								'value' => 'arbrisseau',
							),
						),
						array(
							array(
								'field' => 'field_6304c66b23919',
								'operator' => '!=',
								'value' => 'non visible',
							),
							array(
								'field' => 'field_6304bdf681abb',
								'operator' => '!=',
								'value' => 'arbre',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'grise' => 'grise',
						'gris-brun' => 'gris-brun',
						'brun-orangée' => 'brun-orangée',
						'brune' => 'brune',
						'orange' => 'orange',
						'blanche' => 'blanche',
						'beige' => 'beige',
						'rougeâtre' => 'rougeâtre',
						'marron' => 'marron',
						'marron-gris' => 'marron-gris',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_6304d897b94a1',
			'label' => 'Feuille',
			'name' => 'feuille',
			'type' => 'group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6304d8aeb94a2',
					'label' => 'Présence de feuilles',
					'name' => 'presence_de_feuilles',
					'type' => 'radio',
					'instructions' => 'Les feuilles ne sont jamais visibles.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'visible' => 'visible',
						'jamais visible' => 'jamais visible',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
			),
		),
		array(
			'key' => 'field_6304d9e2b94a5',
			'label' => 'Feuilles visibles',
			'name' => 'feuilles_visibles',
			'type' => 'group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6304d8aeb94a2',
						'operator' => '==',
						'value' => 'visible',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6304d939b94a3',
					'label' => 'Photo de feuilles',
					'name' => 'photo_de_feuilles',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_6304d98fb94a4',
					'label' => 'Phyllotaxie',
					'name' => 'phyllotaxie',
					'type' => 'checkbox',
					'instructions' => 'Les feuilles sont disposées de façon ...',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'alterne spiralée' => 'alterne spiralée',
						'alterne distique' => 'alterne distique',
						'opposée décussée' => 'opposée décussée',
						'verticillée' => 'verticillée',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304da7252e04',
					'label' => 'Type de feuille',
					'name' => 'type_de_feuille',
					'type' => 'checkbox',
					'instructions' => 'et elles sont ...',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'simple' => 'simple',
						'composée' => 'composée',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304dac552e05',
					'label' => 'Limbe des feuilles simples',
					'name' => 'limbe_des_feuilles_simples',
					'type' => 'checkbox',
					'instructions' => 'Le limbe est ...,',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304da7252e04',
								'operator' => '==',
								'value' => 'simple',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'circulaire' => 'circulaire',
						'ovale' => 'ovale',
						'lancéolé' => 'lancéolé',
						'linéaire' => 'linéaire',
						'triangulaire' => 'triangulaire',
						'cordé' => 'cordé',
						'pennatiséqué' => 'pennatiséqué',
						'palmatiséqué' => 'palmatiséqué',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304db6293737',
					'label' => 'Limbe des folioles',
					'name' => 'limbe_des_folioles',
					'type' => 'checkbox',
					'instructions' => 'Le limbe est ...,',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304da7252e04',
								'operator' => '==',
								'value' => 'composée',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'circulaire' => 'circulaire',
						'ovale' => 'ovale',
						'lancéolé' => 'lancéolé',
						'linéaire' => 'linéaire',
						'triangulaire' => 'triangulaire',
						'cordé' => 'cordé',
						'pennatiséqué' => 'pennatiséqué',
						'palmatiséqué' => 'palmatiséqué',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304dbec93738',
					'label' => 'Marge foliaire',
					'name' => 'marge_foliaire',
					'type' => 'checkbox',
					'instructions' => 'à margue folaire ... .',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'entière' => 'entière',
						'lobée' => 'lobée',
						'dentée' => 'dentée',
						'pubescente' => 'pubescente',
						'épineuse' => 'épineuse',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304dc3393739',
					'label' => 'Nervation',
					'name' => 'nervation',
					'type' => 'checkbox',
					'instructions' => 'et à nervation ... .',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'parallèle' => 'parallèle',
						'pennée' => 'pennée',
						'palmée' => 'palmée',
						'peltée' => 'peltée',
						'uninervée' => 'uninervée',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304dc629373a',
					'label' => 'Pétiole',
					'name' => 'petiole',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'présent' => 'présent',
						'absent' => 'absent',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304dc9a9373b',
					'label' => 'Longueur du pétiole',
					'name' => 'longueur_du_petiole',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304dc629373a',
								'operator' => '==',
								'value' => 'présent',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'plus court que le limbe' => 'plus court que le limbe',
						'de la même longueur que le limbe' => 'de la même longueur que le limbe',
						'plus grand que le limbe' => 'plus grand que le limbe',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304dcd49373c',
					'label' => 'Engainant',
					'name' => 'engainant',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304dc629373a',
								'operator' => '==',
								'value' => 'présent',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'engainant' => 'engainant',
						'non engainant' => 'non engainant',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304dee810a78',
					'label' => 'Stipule',
					'name' => 'stipule',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'présents' => 'présents',
						'pas visibles' => 'pas visibles',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304df1810a79',
					'label' => 'Forme et couleur des stipules',
					'name' => 'forme_et_couleur_des_stipules',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304dee810a78',
								'operator' => '==',
								'value' => 'présents',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_6304df4410a7a',
					'label' => 'Feuillage',
					'name' => 'feuillage',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304bdf681abb',
								'operator' => '==',
								'value' => 'arbrisseau',
							),
						),
						array(
							array(
								'field' => 'field_6304bdf681abb',
								'operator' => '==',
								'value' => 'arbre',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'caduc' => 'caduc',
						'marescent' => 'marescent',
						'persistant' => 'persistant',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
			),
		),
		array(
			'key' => 'field_6304e4f591a4b',
			'label' => 'Inflorescence',
			'name' => 'inflorescence',
			'type' => 'group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6304ea4b91a4c',
					'label' => 'Organisation des fleurs',
					'name' => 'organisation_des_fleurs',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'organisées en inflorescence' => 'organisées en inflorescence',
						'solitaires' => 'solitaires',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304ec28c13d6',
					'label' => 'Catégorie',
					'name' => 'categorie',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304ea4b91a4c',
								'operator' => '==',
								'value' => 'organisées en inflorescence',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'une grappe' => 'une grappe',
						'un épi' => 'un épi',
						'une ombelle' => 'une ombelle',
						'un corymbe' => 'un corymbe',
						'un capitule' => 'un capitule',
						'un panicule' => 'un panicule',
						'une cyme bipare' => 'une cyme bipare',
						'une cyme unipare scorpioide' => 'une cyme unipare scorpioide',
						'une cyme multipare' => 'une cyme multipare',
						'autre' => 'autre',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304eccbc13d7',
					'label' => 'Description',
					'name' => 'description',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304ec28c13d6',
								'operator' => '==',
								'value' => 'autre',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_6304eeb9be187',
			'label' => 'Fleur mâle',
			'name' => 'fleur_male',
			'type' => 'group',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6304be7c75bd9',
						'operator' => '!=',
						'value' => 'hermaphrodite',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_6304ef9dbe188',
					'label' => 'Photo',
					'name' => 'photo',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => 5,
					'mime_types' => '.jpg, .jpeg, .png',
				),
				array(
					'key' => 'field_6304f001be189',
					'label' => 'Symétrie',
					'name' => 'symetrie',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'actinomorphe' => 'actinomorphe',
						'zygomorphe' => 'zygomorphe',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304f06dbe18a',
					'label' => 'Hypanthium',
					'name' => 'hypanthium',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'présent' => 'présent',
						'absent' => 'absent',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304f0d3be18b',
					'label' => 'Périanthe',
					'name' => 'perianthe',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'présent' => 'présent',
						'absent' => 'absent',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304f10bbe18c',
					'label' => 'Différenciation du périanthe',
					'name' => 'differenciation_du_perianthe',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304f0d3be18b',
								'operator' => '==',
								'value' => 'absent',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'tépales' => 'tépales',
						'sépales et pétales' => 'sépales et pétales',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304f178be18d',
					'label' => 'Calice',
					'name' => 'calice',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304f10bbe18c',
								'operator' => '==',
								'value' => 'sépales et pétales',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						1 => '1',
						2 => '2',
						3 => '3',
						4 => '4',
						5 => '5',
						6 => '6',
						7 => '7',
						8 => '8',
						9 => '9',
						10 => '10',
						11 => '11',
						12 => '12',
						13 => '13',
						14 => '14',
						15 => '15',
						16 => '16',
						17 => '17',
						18 => '18',
						19 => '19',
						20 => '20',
						'n > 20' => 'n > 20',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304f4812d9ef',
					'label' => 'Soudure du calice',
					'name' => 'soudure_du_calice',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304f10bbe18c',
								'operator' => '==',
								'value' => 'sépales et pétales',
							),
							array(
								'field' => 'field_6304f178be18d',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'soudé sur plus de la moitié de la longueur' => 'soudé sur plus de la moitié de la longueur',
						'soudé sur moins de la moitié de la longueur' => 'soudé sur moins de la moitié de la longueur',
						'libre' => 'libre',
						'partiellement soudés entre eux' => 'partiellement soudés entre eux',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304f5bb2d9f2',
					'label' => 'Corolle',
					'name' => 'corolle',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304f10bbe18c',
								'operator' => '==',
								'value' => 'sépales et pétales',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						1 => '1',
						2 => '2',
						3 => '3',
						4 => '4',
						5 => '5',
						6 => '6',
						7 => '7',
						8 => '8',
						9 => '9',
						10 => '10',
						11 => '11',
						12 => '12',
						13 => '13',
						14 => '14',
						15 => '15',
						16 => '16',
						17 => '17',
						18 => '18',
						19 => '19',
						20 => '20',
						'n > 20' => 'n > 20',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304f698c677e',
					'label' => 'Soudure du calice et de la corolle',
					'name' => 'soudure_du_calice_et_de_la_corolle',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304f10bbe18c',
								'operator' => '==',
								'value' => 'sépales et pétales',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'soudés au calice' => 'soudés au calice',
						'non soudés au calice' => 'non soudés au calice',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304f734c677f',
					'label' => 'Périgone',
					'name' => 'perigone',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304f10bbe18c',
								'operator' => '==',
								'value' => 'tépales',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						1 => '1',
						2 => '2',
						3 => '3',
						4 => '4',
						5 => '5',
						6 => '6',
						7 => '7',
						8 => '8',
						9 => '9',
						10 => '10',
						11 => '11',
						12 => '12',
						13 => '13',
						14 => '14',
						15 => '15',
						16 => '16',
						17 => '17',
						18 => '18',
						19 => '19',
						20 => '20',
						'n > 20' => 'n > 20',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304f7e7c6780',
					'label' => 'Soudure du périgone',
					'name' => 'soudure_du_perigone',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304f734c677f',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'soudé sur plus de la moitié de la longueur' => 'soudé sur plus de la moitié de la longueur',
						'soudé sur moins de la moitié de la longueur' => 'soudé sur moins de la moitié de la longueur',
						'libre' => 'libre',
						'partiellement soudés entre eux' => 'partiellement soudés entre eux',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304f8b6829c8',
					'label' => 'Androcée',
					'name' => 'androcee',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						1 => '1',
						2 => '2',
						3 => '3',
						4 => '4',
						5 => '5',
						6 => '6',
						7 => '7',
						8 => '8',
						9 => '9',
						10 => '10',
						11 => '11',
						12 => '12',
						13 => '13',
						14 => '14',
						15 => '15',
						16 => '16',
						17 => '17',
						18 => '18',
						19 => '19',
						20 => '20',
						'n > 20' => 'n > 20',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304f8f3829c9',
					'label' => 'Soudure de l\'androcée',
					'name' => 'soudure_de_landrocee',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304f8b6829c8',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'soudé sur plus de la moitié de la longueur' => 'soudé sur plus de la moitié de la longueur',
						'soudé sur moins de la moitié de la longueur' => 'soudé sur moins de la moitié de la longueur',
						'libre' => 'libre',
						'partiellement soudés entre eux' => 'partiellement soudés entre eux',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304f99e829ca',
					'label' => 'Soudure androcée-corolle',
					'name' => 'soudure_androcee-corolle',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'soudées à la corolle' => 'soudées à la corolle',
						'non soudées à la corolle' => 'non soudées à la corolle',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304f9ce829cb',
					'label' => 'Soudure androcée-périgone',
					'name' => 'soudure_androcee-perigone',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304f10bbe18c',
								'operator' => '==',
								'value' => 'tépales',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'soudées à la corolle' => 'soudées à la corolle',
						'non soudées à la corolle' => 'non soudées à la corolle',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304fa25829cc',
					'label' => 'Staminodes',
					'name' => 'staminodes',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'présents' => 'présents',
						'absents' => 'absents',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304fb26829cd',
					'label' => 'Nombre de staminodes',
					'name' => 'nombre_de_staminodes',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304fa25829cc',
								'operator' => '==',
								'value' => 'présents',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 1,
					'max' => 50,
					'step' => '',
				),
				array(
					'key' => 'field_6304fc15829ce',
					'label' => 'Couleur principale',
					'name' => 'couleur_principale',
					'type' => 'radio',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'jaune pâle' => 'jaune pâle',
						'jaune vif' => 'jaune vif',
						'rose pâle' => 'rose pâle',
						'rose vif' => 'rose vif',
						'rouge' => 'rouge',
						'violet' => 'violet',
						'blanc' => 'blanc',
						'vert' => 'vert',
						'marron' => 'marron',
						'noir' => 'noir',
						'mauve' => 'mauve',
						'bleu pâle' => 'bleu pâle',
						'bleu vif' => 'bleu vif',
						'orange' => 'orange',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304fc93829cf',
					'label' => 'Pubescence',
					'name' => 'pubescence',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'entièrement glabre' => 'entièrement glabre',
						'pubescente' => 'pubescente',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
					'save_other_choice' => 0,
				),
				array(
					'key' => 'field_6304fcbc829d0',
					'label' => 'Localisation des poils',
					'name' => 'localisation_des_poils',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304fc93829cf',
								'operator' => '==',
								'value' => 'pubescente',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'tous les organes floraux' => 'tous les organes floraux',
						'calice' => 'calice',
						'corolle' => 'corolle',
						'androcée' => 'androcée',
						'gynécée' => 'gynécée',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_6304fdcd68d53',
					'label' => 'Autre caractère',
					'name' => 'autre_caractere',
					'type' => 'text',
					'instructions' => 'Si votre fleur mâle comporte d\'autres caractères intéressants notez les ici',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_6304f0d3be18b',
								'operator' => '==',
								'value' => 'présent',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Ex. : nectaires bien visibles, présence d’une couronne (paracorolle), écailles sur les pétales, présence d’un éperon, présence de fleurs stériles dans les inflorescences, ovaire enveloppé dans un utricule, etc.',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_category',
				'operator' => '==',
				'value' => 'category:bdtfx',
			),
		),
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '66',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

endif;		
